version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres